### ISSUE TITLE
userspace configuration

### ISSUE THREAD

**Issue by boredland** [Manjaro-Sway/manjaro-sway#134]
to ease the pain of upgrades to the skel, we would like to

1. reduce the amount of user-space configuration
2. offer a override & plugin functionality for all tools

- [x] sworkstyle has no functionality for this yet (https://github.com/Lyr-7D1h/swayest_workstyle/issues/11)
- [x] foot (provides support https://codeberg.org/dnkl/foot/issues/659, but did not release yet )
- [x] waybar (provides support https://github.com/Alexays/Waybar/pull/995, pr from our side is ready https://github.com/Manjaro-Sway/desktop-settings/pull/53, release missing https://github.com/Alexays/Waybar/issues/1198)
