### ISSUE TITLE
add a little time tracker

### ISSUE THREAD

**Issue by boredland** [Manjaro-Sway/manjaro-sway#143]
- should be a nice cli tool
- should display start/stop button in waybar

**Comment by Mathew-D** [comment]
Would something like the following work:
https://tailordev.github.io/Watson/

**Comment by boredland** [comment]
exactly! sth. like that. problem with watson is, iirc, that is has projects and tasks. just 'starting' it from waybar wont be possible, I fear.

**Comment by Mathew-D** [comment]
Well what something like https://github.com/mathialo/timer then.

**Comment by S1SYPHOS** [comment]
What about `zeit`: https://github.com/mrusme/zeit (for `waybar` script, see under *Integrations*)

**Comment by boredland** [comment]
I added Zeit to our repository, as I see it now we'd need to:

- [ ]set a default ZEIT_DB location
- [ ] add the waybar module (should be conditionally if zeit installed)
- [ ] add zeit to optdepends
- [ ] install zeit as extra (not sure)

**Comment by boredland** [comment]
Looked a bit into it: imo we can do that script much nicer. It's very simple what there already is (and uses a lot of the waybar without good reason).
